### PR TITLE
C Client Compatibility

### LINKED ISSUE #82: C SDK Expects to0d Hash
When Go-FDO runs as DI and RV (a.k.a. auto-TO0) it sets a to0d hash with SHA256 algorithm and no hash value. In the C SDK this results in an error.

```
ERROR:[fdo_hash_read():755] Invalid Hash: Unable to decode length of hash!
ERROR:[msg33():115] TO1.RVRedirect: Failed to read to1dTo0dHash
ERROR:[fdo_process_states():194] Error occurred while processing Type 33
```

Instead, Go should send a conspicuous hash value, like all zeroes.

### PR DESCRIPTION
**Pull request by bkgoodman**
Minor changes for compatibility with C-library

Fixes #82

### CODE REVIEW

File: custom/di.go [hunk 1]
```diff
@@ -45,6 +45,7 @@ type DeviceMfgInfo struct {
 	SerialNumber string
 	DeviceInfo   string
 	CertInfo     cbor.X509CertificateRequest
+	MACaddress   string
```
Comment (ben-krieger) [inline custom/di.go:48]: While this fixes C compatibility, it breaks Java compatibility.

I suggest we resolve the C issue on the C side of things. See this issue: https://github.com/fido-device-onboard/client-sdk-fidoiot/issues/298

File: di.go [hunk 2]
```diff
@@ -443,7 +443,10 @@ func (s *DIServer[T]) maybeAutoTO0(ctx context.Context, ov *Voucher) error {
 	sign1 := cose.Sign1[protocol.To1d, []byte]{
 		Payload: cbor.NewByteWrap(protocol.To1d{
 			RV:       s.AutoTO0Addrs,
-			To0dHash: protocol.Hash{Algorithm: protocol.Sha256Hash},
+			To0dHash: protocol.Hash{
+                Algorithm: protocol.Sha256Hash,
+                Value: make([]byte,32),
+                },
```
Comment (ben-krieger) [inline di.go:449]: Can you make sure to run `gofmt` on the code?

**Review by ben-krieger — APPROVED** [review]

File: custom/di.go (hunk 1 above)
Comment (ben-krieger) [reply custom/di.go]: The other option is to use a custom type `T` in `DIServer[T]` which has the 6th field.

You'd then just have to change two fields in the DI Server to use the new type.

```go
SignDeviceCertificate: yourCustomSignDeviceCertificate(state),
// This can stay the same
DeviceInfo: func(_ context.Context, info *YourCustomDeviceMfgInfo, _ []*x509.Certificate) (string, protocol.KeyType, protocol.KeyEncoding, error) {
	return info.DeviceInfo, info.KeyType, info.KeyEncoding, nil
},
```
